<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-BBV4M2VF" failures="1" tests="6" name="Smoke Test" time="0.643" errors="0" timestamp="2020-07-06T01:49:19 IST">
  <testcase classname="com.mycompany.app.AppiumTest" name="appiumTest" time="0.009"/>
  <testcase classname="com.mycompany.app.AppiumTest" name="india" time="0.001"/>
  <testcase classname="com.mycompany.app.AppiumTest" name="random" time="0.003"/>
  <testcase classname="com.mycompany.app.SeleniumTest" name="selinumTest" time="0.001"/>
  <testcase classname="com.mycompany.app.Api" name="api" time="0.001"/>
  <testcase classname="com.mycompany.app.DDT" name="validateLogin" time="0.573">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:458)
at com.mycompany.app.DDT.validateLogin(DDT.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validateLogin -->
</testsuite> <!-- Smoke Test -->
